### 판매자 회원 가입
POST http://localhost:3000/seller/signUp
Content-Type: application/json

{
  "email": "seller1@example.com",
  "username": "seller1",
  "password": "seller1-password"
}

### 판매자 접근 토큰 발행
POST http://localhost:3000/seller/issueToken
Content-Type: application/json

{
    "email": "seller1@example.com",
    "password": "seller1-password"
  }

###

